theme = "sonokai"

[editor]
line-number = "relative"
bufferline = "always"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { k = "normal_mode" }
